### ISSUE TITLE
info about this project

### ISSUE THREAD

**Issue by ghost** [paulsapps/7-Gears#1]
Hi paul, is this project completed or, in other words, is the game completable?

**Comment by MrSapps** [comment]
This project was a very early tech demo that didn't get far at all. If I ever get around to working on this again its probably going to be quite some time away.

Maybe I should mark this as an archived repo until I get back to it.

**Comment by ghost** [comment]
Ok, it uses opengl 3.x I believe because sdl cant detect my opengl. So I could not ue it anyway. Thanks
